---
name: Build S3GW Container
on:

  # TODO: trigger only on new radosgw binary
  push:
    branches:
      - "s3gw"

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build-radosgw.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ceph
          submodules: recursive

      - name: Checkout s3gw-core
        uses: actions/checkout@v3
        with:
          repository: 'aquarist-labs/s3gw-core'
          ref: 'main'
          path: 's3gw-core'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Artifact Identifier
        id: artifact_id
        run: |
          ARTIFACT_ID=radosgw-$GITHUB_SHA
          echo "::set-output name=artifact_id::$ATIFACT_ID"

      - name: Download Radogw Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.artifact_id.outputs.artifact_id }}

      - name: Unpack Artifacts
        run: |
          tar -xvf ${{ steps.artifact_id.outputs.artifact_id }}

      - name: Build S3GW Container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mrohrich/s3gw:latest
          file: s3gw-core/build/Dockerfile.build-container
          context: s3gw-core/build
