---
name: Build Radosgw
on:
  schedule:
    - cron: '0 0 * * 0'  # refresh ccache every sunday night

  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'ceph'
          submodules: 'recursive'

      - name: Create CCache Timestamp
        id: ccache_timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%Y-%m-%d-%H:%M:%S)"

      - name: Cache CCache Files
        uses: actions/cache@v3.0.4
        with:
          path: ceph/build.ccache
          key: ccache-${{ steps.ccache_timestamp.outputs.timestamp }}
          restore-keys: |
            ccache-

      - name: Build radosgw Binary
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE/ceph:/srv/ceph \
            -e NPROC=4 \
            mrohrich/buildenv-radosgw:latest

      - name: Compress Build Results
        run: |
          tar -czvf build-results.tar.gz ceph/build

      - name: Generate Artifact Identifier
        id: artifact_id
        run: |
          ARTIFACT_ID=radosgw-$GITHUB_SHA
          echo "::set-output name=artifact_id::$ARTIFACT_ID"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact_id.outputs.artifact_id }}
          path: build-results.tar.gz
