---
name: Test Radosgw
on:
  push:
    branches:
      - '*'  # TODO: remove this trigger once the pipeline is merged.

  pull_request:
    branches:
      - "s3gw"

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build-radosgw.yml

  test:
    runs-on: ubuntu-latest
    needs:
      - call-build-workflow

    steps:
      - name: Checkout s3gw-core
        uses: actions/checkout@v3
        with:
          repository: 'aquarist-labs/s3gw-core'
          ref: 'main'
          path: 's3gw-core'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Artifact Identifier
        id: artifact_id
        run: |
          ARTIFACT_ID=radosgw-$GITHUB_SHA
          echo "::set-output name=artifact_id::$ARTIFACT_ID"

      - name: Download Radogw Artifacts
        id: download_artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.artifact_id.outputs.artifact_id }}

      - name: Unpack Artifacts
        run: |
          tar -xvf build-results.tar.gz
          ls -la
          # TODO: Run tests here
