---
name: Test Radosgw
on:
  pull_request:
    branches:
      - "s3gw"

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build-radosgw.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs:
      - call-build-workflow

    steps:
      - name: Checkout s3gw-core
        uses: actions/checkout@v3
        with:
          repository: 'aquarist-labs/s3gw-core'
          ref: 'main'
          path: 's3gw-core'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            network=host

      - name: Run Tests
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          mkdir storage
          docker run \
            -v ./storage:/data \
            -p 7480:7480 \
            $DOCKERHUB_USERNAME/s3gw:${{ needs.call-build-workflow.outputs.short_sha }}

          echo "Running Tests:\n"

          curl -vk http://localhost:7480
          # TODO: Run tests here
